// <auto-generated />
using System;
using KinderConnect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KinderConnect.Data.Migrations
{
    [DbContext(typeof(KinderConnectDbContext))]
    [Migration("20240415092941_SeedMoreTeachers")]
    partial class SeedMoreTeachers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("KinderConnect.Data.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "We learn to draw circles and triangles :)",
                            IsActive = false,
                            Name = "Drawing"
                        },
                        new
                        {
                            Id = 2,
                            Description = "We learn to write the Alphabet :)",
                            IsActive = false,
                            Name = "Writing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "We play a lot of football and volleyball :)",
                            IsActive = false,
                            Name = "Play"
                        });
                });

            modelBuilder.Entity("KinderConnect.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("702de3dd-c1e7-4f40-9131-623aadb7e765"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6199ec75-40c5-4057-824e-b280185f49c9",
                            DateOfBirth = new DateTime(1972, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mrpopov@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Lyubomir",
                            Gender = "male",
                            IsActive = false,
                            LastName = "Popov",
                            LockoutEnabled = false,
                            NormalizedEmail = "MRPOPOV@gmail.com",
                            NormalizedUserName = "MR.POPOV",
                            PasswordHash = "AQAAAAEAACcQAAAAEKD7ue2lT9/3kT1BsIV9uXwJgQ+j1atLihMxsAncN8qXuiOy5j7pTDYoKPLiS3Sslg==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Mr.Popov"
                        },
                        new
                        {
                            Id = new Guid("c3010f38-ec8b-4c80-9599-e8fdada9299f"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fe039e88-dbba-45b3-8726-73037298e626",
                            DateOfBirth = new DateTime(1971, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mrbuhov@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Mustafa",
                            Gender = "male",
                            IsActive = false,
                            LastName = "Buhov",
                            LockoutEnabled = false,
                            NormalizedEmail = "MRBUHOV@GMAIL.COM",
                            NormalizedUserName = "MR.BUHOV",
                            PasswordHash = "AQAAAAEAACcQAAAAEKD7ue2lT9/3kT1BsIV9uXwJgQ+j1atLihMxsAncN8qXuiOy5j7pTDYoKPLiS3Sslg==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Mr.Buhov"
                        },
                        new
                        {
                            Id = new Guid("bbfe1b04-2741-4440-9334-595cb40a9f64"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5e275e81-8ba0-4a09-9cb1-46e9af158276",
                            DateOfBirth = new DateTime(1990, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "parent1@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Father",
                            Gender = "male",
                            IsActive = false,
                            LastName = "Mitev",
                            LockoutEnabled = false,
                            NormalizedEmail = "PARENT1@GMAIL.COM",
                            NormalizedUserName = "PARENT1",
                            PasswordHash = "AQAAAAEAACcQAAAAEKD7ue2lT9/3kT1BsIV9uXwJgQ+j1atLihMxsAncN8qXuiOy5j7pTDYoKPLiS3Sslg==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Parent1"
                        },
                        new
                        {
                            Id = new Guid("b785b0d0-3d8c-4c37-a304-e2c41dcab31a"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a48ceaeb-ff86-4ebd-860b-958b51abe5e7",
                            DateOfBirth = new DateTime(1992, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "parent2@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Mother",
                            Gender = "female",
                            IsActive = false,
                            LastName = "Ivanova",
                            LockoutEnabled = false,
                            NormalizedEmail = "PARENT2@GMAIL.COM",
                            NormalizedUserName = "PARENT2",
                            PasswordHash = "AQAAAAEAACcQAAAAEKD7ue2lT9/3kT1BsIV9uXwJgQ+j1atLihMxsAncN8qXuiOy5j7pTDYoKPLiS3Sslg==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Parent2"
                        },
                        new
                        {
                            Id = new Guid("3851aad2-a5a3-462d-bf39-d8b0b41f0ad6"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ef0de57e-05e3-4dba-995d-b3b667bb8b08",
                            DateOfBirth = new DateTime(2000, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "parent3@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Emily",
                            Gender = "female",
                            IsActive = false,
                            LastName = "Cankova",
                            LockoutEnabled = false,
                            NormalizedEmail = "PARENT3@GMAIL.COM",
                            NormalizedUserName = "PARENT3",
                            PasswordHash = "AQAAAAEAACcQAAAAEKD7ue2lT9/3kT1BsIV9uXwJgQ+j1atLihMxsAncN8qXuiOy5j7pTDYoKPLiS3Sslg==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Parent3"
                        },
                        new
                        {
                            Id = new Guid("47d28c7b-a4fc-4617-bbbd-60b05a0bfd45"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e3a94711-6c6c-4a92-8031-7ee82410a322",
                            DateOfBirth = new DateTime(2000, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mrsamelia@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Amelia",
                            Gender = "female",
                            IsActive = false,
                            LastName = "Avita",
                            LockoutEnabled = false,
                            NormalizedEmail = "MRSAMELIA@GMAIL.COM",
                            NormalizedUserName = "MRS.AMELIA",
                            PasswordHash = "AQAAAAEAACcQAAAAEKD7ue2lT9/3kT1BsIV9uXwJgQ+j1atLihMxsAncN8qXuiOy5j7pTDYoKPLiS3Sslg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "Z9Y8X7W6V5U4T3S2R1Q0P9O8N7M6L5K",
                            TwoFactorEnabled = false,
                            UserName = "Mrs.Amelia"
                        },
                        new
                        {
                            Id = new Guid("37ed60d0-efe7-4d5a-89c1-8169c7ae008f"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d07244b0-5114-4d7a-899e-75a23d555041",
                            DateOfBirth = new DateTime(1999, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mrsava@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Ava",
                            Gender = "female",
                            IsActive = false,
                            LastName = "Alita",
                            LockoutEnabled = false,
                            NormalizedEmail = "MRSAVA@GMAIL.COM",
                            NormalizedUserName = "MRS.AVA",
                            PasswordHash = "AQAAAAEAACcQAAAAEKD7ue2lT9/3kT1BsIV9uXwJgQ+j1atLihMxsAncN8qXuiOy5j7pTDYoKPLiS3Sslg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "H2G3F4E5D6C7B8A9Z0Y1X2W3V4U5T6S",
                            TwoFactorEnabled = false,
                            UserName = "Mrs.Ava"
                        },
                        new
                        {
                            Id = new Guid("ffa6f8eb-02f7-4246-aa59-f7ce6d2be5ff"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0835fcc4-1495-4b70-bdda-8a259a865f92",
                            DateOfBirth = new DateTime(1998, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mrsaurora@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Aurora",
                            Gender = "female",
                            IsActive = false,
                            LastName = "Gastambide",
                            LockoutEnabled = false,
                            NormalizedEmail = "MRSAURORA@GMAIL.COM",
                            NormalizedUserName = "MRS.AURORA",
                            PasswordHash = "AQAAAAEAACcQAAAAEKD7ue2lT9/3kT1BsIV9uXwJgQ+j1atLihMxsAncN8qXuiOy5j7pTDYoKPLiS3Sslg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "M1N2O3P4Q5R6S7T8U9V0A1B2C3D4E5F",
                            TwoFactorEnabled = false,
                            UserName = "Mrs.Aurora"
                        },
                        new
                        {
                            Id = new Guid("31c9d7c4-5b0e-46b5-a6db-0ed766d6b563"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1b6bbafc-e1e1-4bca-91cb-36f29c303502",
                            DateOfBirth = new DateTime(2001, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mrssavka@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Savka",
                            Gender = "female",
                            IsActive = false,
                            LastName = "Ivanovich",
                            LockoutEnabled = false,
                            NormalizedEmail = "MRSSAVKA@GMAIL.COM",
                            NormalizedUserName = "MRS.SAVKA",
                            PasswordHash = "AQAAAAEAACcQAAAAEKD7ue2lT9/3kT1BsIV9uXwJgQ+j1atLihMxsAncN8qXuiOy5j7pTDYoKPLiS3Sslg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "J9K8L7M6N5O4P3Q2R1S0T9U8V7W6X5Y",
                            TwoFactorEnabled = false,
                            UserName = "Mrs.Savka"
                        });
                });

            modelBuilder.Entity("KinderConnect.Data.Models.AttendanceChild", b =>
                {
                    b.Property<Guid>("AttendanceRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit");

                    b.HasKey("AttendanceRecordId", "ChildId");

                    b.HasIndex("ChildId");

                    b.ToTable("AttendanceChildren");
                });

            modelBuilder.Entity("KinderConnect.Data.Models.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("TeacherId");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("KinderConnect.Data.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(3500)
                        .HasColumnType("nvarchar(3500)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "KinderConnect's Headmaster",
                            Content = "Outdoor play is crucial for children's development. It provides them with opportunities to explore their environment, develop their physical skills, and engage in imaginative play.\r\nResearch has shown that children who engage in regular outdoor play have better physical health, including stronger immune systems and reduced risk of obesity. Outdoor play also promotes mental well-being, as it allows children to release energy, reduce stress, and improve their mood.\r\nAdditionally, outdoor play encourages creativity and problem-solving skills. When children play outdoors, they are free to explore and interact with their surroundings, which stimulates their imagination and encourages them to think critically.\r\nFurthermore, outdoor play fosters social skills and cooperation. Children who play together outdoors learn to share, take turns, and communicate effectively with their peers. They also develop empathy and understanding as they navigate social interactions and resolve conflicts.\r\nIn conclusion, outdoor play is essential for children's overall development. It provides numerous physical, mental, and social benefits that contribute to their health and well-being.",
                            CreatedOn = new DateTime(2024, 3, 29, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://example.com/outdoor-play-image.jpg",
                            Title = "The Importance of Outdoor Play for Children"
                        },
                        new
                        {
                            Id = 2,
                            Author = "KinderConnect's Headmaster",
                            Content = "Ensuring a safe environment is essential for preschoolers to thrive. Young children are naturally curious and eager to explore their surroundings, so it's important to take steps to prevent accidents and injuries.\r\nOne way to create a safe environment for preschoolers is to childproof the space. This includes securing furniture and appliances, covering electrical outlets, and removing small objects that could be choking hazards. It's also important to keep hazardous substances out of reach and store them securely.\r\nIn addition to childproofing, it's essential to supervise preschoolers closely, especially when they're engaged in activities that pose a risk of injury. By keeping a watchful eye on them, caregivers can quickly intervene if they encounter any dangers.\r\nFurthermore, teaching preschoolers about safety rules and procedures is crucial. This includes educating them about fire safety, road safety, and personal boundaries. By empowering children with knowledge and skills, caregivers can help them make safer choices and avoid accidents.\r\nOverall, creating a safe environment for preschoolers requires careful planning, supervision, and education. By taking these steps, caregivers can ensure that young children have the opportunity to learn and grow in a secure and nurturing environment.",
                            CreatedOn = new DateTime(2024, 3, 29, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://example.com/safe-environment-image.jpg",
                            Title = "Creating a Safe Environment for Preschoolers"
                        },
                        new
                        {
                            Id = 3,
                            Author = "KinderConnect's Headmaster",
                            Content = "Storytelling has numerous benefits for young children, including enhancing their language development, cognitive skills, and emotional intelligence.\r\nFirstly, storytelling promotes language development by exposing children to rich and varied vocabulary. When children listen to stories, they learn new words and phrases, which helps expand their vocabulary and improve their comprehension skills. Additionally, storytelling helps children develop their speaking skills as they retell stories and engage in discussions about the plot, characters, and themes.\r\nFurthermore, storytelling stimulates cognitive skills such as memory, imagination, and problem-solving. When children listen to stories, they use their imagination to visualize the characters and events, which enhances their creativity and critical thinking skills. Additionally, storytelling helps children develop their memory skills as they recall details from the story and make connections between different events.\r\nMoreover, storytelling encourages emotional intelligence by helping children identify and express their feelings. When children listen to stories with relatable characters and themes, they learn about empathy, compassion, and resilience. Storytelling also provides children with opportunities to explore complex emotions and learn coping strategies for dealing with difficult situations.\r\nIn conclusion, storytelling is a valuable tool for early childhood education. It promotes language development, cognitive skills, and emotional intelligence, providing children with a solid foundation for learning and growth.",
                            CreatedOn = new DateTime(2024, 3, 29, 16, 50, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://example.com/storytelling-image.jpg",
                            Title = "Benefits of Storytelling in Early Childhood Education"
                        });
                });

            modelBuilder.Entity("KinderConnect.Data.Models.Child", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Allergies")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("ClassroomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MedicalInformation")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ParentGuardianContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ParentGuardianId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("ParentGuardianId");

                    b.ToTable("Children");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5c90cfb4-b710-4a9b-b2a6-9f7880152388"),
                            Age = 4,
                            ClassroomId = new Guid("632bc679-3cc2-45b7-971b-6a92105321de"),
                            DateOfBirth = new DateTime(2020, 5, 5, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Luna",
                            Gender = "female",
                            ImageUrl = "https://img.freepik.com/premium-photo/smiling-baby-girl-3-4-year-old-wearing-knitted-red-sweater-posing-nature-background-close-up-looking-camera-childhood-autumn-season_260913-2064.jpg",
                            IsActive = false,
                            LastName = "Little",
                            ParentGuardianContact = "+1987654321",
                            ParentGuardianId = new Guid("bbfe1b04-2741-4440-9334-595cb40a9f64")
                        },
                        new
                        {
                            Id = new Guid("b868a0a1-c4d6-48c7-86df-312985816bf1"),
                            Age = 3,
                            ClassroomId = new Guid("632bc679-3cc2-45b7-971b-6a92105321de"),
                            DateOfBirth = new DateTime(2021, 3, 3, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Chicken",
                            Gender = "male",
                            ImageUrl = "https://onebighappyphoto.com/wp-content/uploads/2-year-old-boy-and-family-photoshoot-2951-One-Big-Happy-Photo.jpg",
                            IsActive = false,
                            LastName = "Little",
                            ParentGuardianContact = "+1987654321",
                            ParentGuardianId = new Guid("bbfe1b04-2741-4440-9334-595cb40a9f64")
                        },
                        new
                        {
                            Id = new Guid("362c8db9-7cb1-46e9-9f08-f754eeeace63"),
                            Age = 4,
                            ClassroomId = new Guid("958b5667-9055-40a7-b7b2-81c19afe3329"),
                            DateOfBirth = new DateTime(2020, 3, 10, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Leo",
                            Gender = "male",
                            ImageUrl = "https://www.shutterstock.com/image-photo/happy-five-year-old-european-600nw-278349572.jpg",
                            IsActive = false,
                            LastName = "Doodle",
                            ParentGuardianContact = "+1234567890",
                            ParentGuardianId = new Guid("b785b0d0-3d8c-4c37-a304-e2c41dcab31a")
                        },
                        new
                        {
                            Id = new Guid("a9362115-d090-466d-96b3-7857b0af9bad"),
                            Age = 5,
                            ClassroomId = new Guid("958b5667-9055-40a7-b7b2-81c19afe3329"),
                            DateOfBirth = new DateTime(2019, 6, 15, 14, 45, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mila",
                            Gender = "female",
                            ImageUrl = "https://people.com/thmb/PUJBCZ6e6-0hakU8up3vt6TJkZE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():focal(749x0:751x2)/Imi-Schneider4-f5ffc7e6f4d948fb9e40d9c788acc71c.jpg",
                            IsActive = false,
                            LastName = "Doodle",
                            ParentGuardianContact = "+1234567890",
                            ParentGuardianId = new Guid("b785b0d0-3d8c-4c37-a304-e2c41dcab31a")
                        },
                        new
                        {
                            Id = new Guid("e0e47953-506b-4ee8-ae9d-b312519ccf10"),
                            Age = 4,
                            ClassroomId = new Guid("958b5667-9055-40a7-b7b2-81c19afe3329"),
                            DateOfBirth = new DateTime(2020, 3, 10, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Emma",
                            Gender = "female",
                            ImageUrl = "https://previews.123rf.com/images/mashiki/mashiki1802/mashiki180200333/96303002-close-up-indoor-portrait-of-cute-happy-2-years-old-baby-girl-in-pink-sweater.jpg",
                            IsActive = false,
                            LastName = "Malinkova",
                            ParentGuardianContact = "+1234567890",
                            ParentGuardianId = new Guid("b785b0d0-3d8c-4c37-a304-e2c41dcab31a")
                        },
                        new
                        {
                            Id = new Guid("82c893d9-2e52-4fd0-8cbb-ffb2af76e323"),
                            Age = 6,
                            ClassroomId = new Guid("c12f8035-d854-4cdc-bad7-489237b10fdf"),
                            DateOfBirth = new DateTime(2018, 1, 20, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ethan",
                            Gender = "male",
                            ImageUrl = "https://cdn.cdnparenting.com/articles/2018/08/643990666-H.webp",
                            IsActive = false,
                            LastName = "Mathews",
                            ParentGuardianContact = "+1122334455",
                            ParentGuardianId = new Guid("73690111-8cdc-4e37-91c2-143c674f324f")
                        },
                        new
                        {
                            Id = new Guid("3bd8a6fc-afd7-4b65-b208-751cfc41433c"),
                            Age = 7,
                            ClassroomId = new Guid("c12f8035-d854-4cdc-bad7-489237b10fdf"),
                            DateOfBirth = new DateTime(2017, 4, 25, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ava",
                            Gender = "female",
                            ImageUrl = "https://images.fineartamerica.com/images/artworkimages/mediumlarge/1/portrait-of-a-girl-seven-years-old-with-blond-hair-and-white-dress-elena-saulich.jpg",
                            IsActive = false,
                            LastName = "Mathews",
                            ParentGuardianContact = "+1122334455",
                            ParentGuardianId = new Guid("73690111-8cdc-4e37-91c2-143c674f324f")
                        },
                        new
                        {
                            Id = new Guid("cf4e2dba-2617-4274-b6ad-2e5ba08354e3"),
                            Age = 10,
                            ClassroomId = new Guid("4faa63ab-f5f8-45ae-bdc4-2eb42ca9b266"),
                            DateOfBirth = new DateTime(2013, 8, 12, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Oliver",
                            Gender = "male",
                            ImageUrl = "https://www.telegram.com/gcdn/authoring/2019/10/21/NTEG/ghows-WT-955ebf6b-6734-21c5-e053-0100007f81d9-9950fec9.jpeg",
                            IsActive = false,
                            LastName = "Techton",
                            ParentGuardianContact = "+9988776655",
                            ParentGuardianId = new Guid("c3010f38-ec8b-4c80-9599-e8fdada9299f")
                        },
                        new
                        {
                            Id = new Guid("f6bc6e8c-4e55-4f75-b18c-8d5b9c2d720b"),
                            Age = 11,
                            ClassroomId = new Guid("4faa63ab-f5f8-45ae-bdc4-2eb42ca9b266"),
                            DateOfBirth = new DateTime(2012, 11, 8, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sophie",
                            Gender = "female",
                            ImageUrl = "https://media.istockphoto.com/id/1035407268/photo/portrait-of-beautiful-girl-of-10-11-years-old-child-with-perfect-white-smile-isolated-on.jpg?s=612x612&w=0&k=20&c=wW_X1ZqF-i5acks0o_nSaL3yuDQgxIhmbCyXXUMMIBE=",
                            IsActive = false,
                            LastName = "Techton",
                            ParentGuardianContact = "+9988776655",
                            ParentGuardianId = new Guid("c3010f38-ec8b-4c80-9599-e8fdada9299f")
                        });
                });

            modelBuilder.Entity("KinderConnect.Data.Models.Classroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MaximumAge")
                        .HasColumnType("int");

                    b.Property<int>("MinimumAge")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<decimal>("TutionFee")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("632bc679-3cc2-45b7-971b-6a92105321de"),
                            CreatedOn = new DateTime(2024, 4, 15, 12, 29, 40, 711, DateTimeKind.Local).AddTicks(8337),
                            ImageUrl = "https://pbs.twimg.com/profile_images/557241923597914112/wuYMY-Sj_400x400.png",
                            Information = "Nature walks.Sensory play with natural materials.Learning about different animals and habitats.Creative storytelling sessions",
                            IsActive = false,
                            MaximumAge = 3,
                            MinimumAge = 0,
                            Name = "Little Explorers",
                            TotalSeats = 25,
                            TutionFee = 100m
                        },
                        new
                        {
                            Id = new Guid("958b5667-9055-40a7-b7b2-81c19afe3329"),
                            CreatedOn = new DateTime(2024, 4, 15, 12, 29, 40, 711, DateTimeKind.Local).AddTicks(8415),
                            ImageUrl = "https://www.abnewswire.com/uploads/1692132999.jpeg",
                            Information = "Art studio with easels and drawing tables.Variety of art supplies and materials.Display area for showcasing student artwork.Cozy reading corner for inspiration",
                            IsActive = false,
                            MaximumAge = 6,
                            MinimumAge = 3,
                            Name = "Doodle Den",
                            TotalSeats = 25,
                            TutionFee = 150m
                        },
                        new
                        {
                            Id = new Guid("5f740711-79e5-457f-81a7-c73557d0074f"),
                            CreatedOn = new DateTime(2024, 4, 15, 12, 29, 40, 711, DateTimeKind.Local).AddTicks(8424),
                            ImageUrl = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjy2CRd52Daq6LiABMz5N0pCnh9Ac9o4ccMvXoxUPmMPMyF9zhxcywuRhwWc2JA6NFcyrDc_j79bmvDk3V15JwmEuJ0v6LVC1bE_0V9W0WSOGs7nwDwyIJ707ej3Kz4QiAdw9ufVec4GAF18Cm5D-UJufeUzMIkqnaOVYWHrk44DbfkaDgKJIto6T02/s1748/teacher%20teaching%20math.png",
                            Information = "Hands-on math activities.Problem-solving challenges.Introduction to basic math concepts.Fun math games.",
                            IsActive = false,
                            MaximumAge = 9,
                            MinimumAge = 6,
                            Name = "Math Whizzes",
                            TotalSeats = 30,
                            TutionFee = 180m
                        },
                        new
                        {
                            Id = new Guid("60cff593-6660-4a7f-8c09-e02a5c209821"),
                            CreatedOn = new DateTime(2024, 4, 15, 12, 29, 40, 711, DateTimeKind.Local).AddTicks(8430),
                            ImageUrl = "https://www.nationalgeographic.org/wp-content/uploads/2021/10/Explorer-Classroom-Ryan-Carney_National-Geographic-scaled.jpeg",
                            Information = "Basic coding for kids.Robotics and engineering projects.Introduction to technology.Creative digital art.",
                            IsActive = false,
                            MaximumAge = 10,
                            MinimumAge = 7,
                            Name = "Tech Explorers",
                            TotalSeats = 30,
                            TutionFee = 200m
                        },
                        new
                        {
                            Id = new Guid("7f624c7e-f824-417c-9c3b-7ae366918397"),
                            CreatedOn = new DateTime(2024, 4, 15, 12, 29, 40, 711, DateTimeKind.Local).AddTicks(8439),
                            ImageUrl = "https://beauvoirmusic.com/wp-content/uploads/2022/08/BMMClass.ILA0070edit1-1024x768.jpg",
                            Information = "Introduction to musical instruments.Music theory basics.Group singing and performances.Fun rhythm and melody activities.",
                            IsActive = false,
                            MaximumAge = 8,
                            MinimumAge = 5,
                            Name = "Music Makers",
                            TotalSeats = 20,
                            TutionFee = 170m
                        },
                        new
                        {
                            Id = new Guid("0101ab59-602e-44ac-8ba8-c79fb24ac7ba"),
                            CreatedOn = new DateTime(2024, 4, 15, 12, 29, 40, 711, DateTimeKind.Local).AddTicks(8445),
                            ImageUrl = "https://scienceexplorers.com/wp-content/uploads/2023/09/Academic-Overview-Science-Explorers-01.jpg",
                            Information = "Hands-on science experiments.Discovering nature and the universe.Introduction to scientific concepts.Creative science projects.",
                            IsActive = false,
                            MaximumAge = 12,
                            MinimumAge = 8,
                            Name = "Science Explorers",
                            TotalSeats = 35,
                            TutionFee = 190m
                        },
                        new
                        {
                            Id = new Guid("fdf1e5c7-a73a-4d08-aaf1-944d4393c411"),
                            CreatedOn = new DateTime(2024, 4, 15, 12, 29, 40, 711, DateTimeKind.Local).AddTicks(8457),
                            ImageUrl = "https://ksspreschool.com/wp-content/uploads/2021/12/KSS-Preschool-English-Skills-and-Language-Immersion.jpeg",
                            Information = "Introduction to new languages.Interactive language games.Cultural learning experiences.Basic vocabulary and phrases.",
                            IsActive = false,
                            MaximumAge = 9,
                            MinimumAge = 6,
                            Name = "Language Learners",
                            TotalSeats = 25,
                            TutionFee = 160m
                        },
                        new
                        {
                            Id = new Guid("2f342a1c-72d6-4b2f-b5b0-4ddcf33f1d2f"),
                            CreatedOn = new DateTime(2024, 4, 15, 12, 29, 40, 711, DateTimeKind.Local).AddTicks(8462),
                            ImageUrl = "https://i.ytimg.com/vi/fIZR5Ib1p_w/maxresdefault.jpg",
                            Information = "Introduction to various sports.Physical fitness activities.Team-building exercises.Healthy competition and fun.",
                            IsActive = false,
                            MaximumAge = 11,
                            MinimumAge = 7,
                            Name = "Sports Stars",
                            TotalSeats = 40,
                            TutionFee = 210m
                        });
                });

            modelBuilder.Entity("KinderConnect.Data.Models.ClassroomTeacher", b =>
                {
                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TeacherId", "ClassroomId");

                    b.HasIndex("ClassroomId");

                    b.ToTable("ClassroomsTeachers");
                });

            modelBuilder.Entity("KinderConnect.Data.Models.Qualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Qualifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A bachelor's degree in early childhood education prepares teachers with comprehensive knowledge and skills in child development, curriculum design, assessment, and family engagement. This qualification enables educators to implement evidence-based practices and support children's holistic development.",
                            IsActive = false,
                            Name = "Bachelor's Degree in Early Childhood Education"
                        },
                        new
                        {
                            Id = 2,
                            Description = "This qualification equips teachers with essential knowledge and skills to effectively engage and educate young children in a kindergarten setting. It covers topics such as child development, curriculum planning, and fostering a nurturing learning environment.",
                            IsActive = false,
                            Name = "Early Childhood Education Certificate"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The CDA credential is a nationally recognized certification for early childhood professionals. It emphasizes the importance of nurturing children's physical, social, emotional, and cognitive development. Teachers with a CDA credential demonstrate competence in providing high-quality care and education to young children.",
                            IsActive = false,
                            Name = "Child Development Associate (CDA) Credential"
                        });
                });

            modelBuilder.Entity("KinderConnect.Data.Models.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QualificationId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TeacherUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QualificationId");

                    b.HasIndex("TeacherUserId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe9af2e3-22af-4583-84f0-11a19bb08533"),
                            ImageUrl = "https://i.guim.co.uk/img/media/b897974dce4559ebe02af27e10c475068ead46a8/0_0_4000_2400/master/4000.jpg?width=1200&height=1200&quality=85&auto=format&fit=crop&s=a53a3c7714a215af7051daea5b14971c",
                            QualificationId = 1,
                            Summary = "Inspires young minds in the kindergarten classroom with his passion for storytelling and language. With a nurturing and supportive approach, Lyubomir guides children on a journey of exploration and discovery through the world of writing. He encourages creativity and self-expression, helping students develop foundational writing skills such as letter formation, phonics, and basic sentence structure.",
                            TeacherUserId = new Guid("702de3dd-c1e7-4f40-9131-623aadb7e765")
                        },
                        new
                        {
                            Id = new Guid("70f60860-e15e-4756-978e-e620b0f69775"),
                            ImageUrl = "https://img.freepik.com/premium-photo/old-male-teacher-portrait-closeup-face-professor-teacher-blackboard-isolated_265223-53892.jpg",
                            QualificationId = 1,
                            Summary = "A dedicated drawing teacher, brings creativity and warmth to the kindergarten classroom as he introduces young children to the world of artistic expression through drawing. With a gentle and encouraging approach, Mustafa fosters the development of fine motor skills, creativity, and self-expression in his students. He designs engaging drawing activities tailored to the unique interests and abilities of each child, from exploring simple shapes to creating imaginative scenes.",
                            TeacherUserId = new Guid("c3010f38-ec8b-4c80-9599-e8fdada9299f")
                        });
                });

            modelBuilder.Entity("KinderConnect.Data.Models.TeacherQualification", b =>
                {
                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QualificationId")
                        .HasColumnType("int");

                    b.HasKey("TeacherId", "QualificationId");

                    b.HasIndex("QualificationId");

                    b.ToTable("TeachersQualifications");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KinderConnect.Data.Models.AttendanceChild", b =>
                {
                    b.HasOne("KinderConnect.Data.Models.AttendanceRecord", "AttendanceRecord")
                        .WithMany("AttendanceChildren")
                        .HasForeignKey("AttendanceRecordId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("KinderConnect.Data.Models.Child", "Child")
                        .WithMany("AttendanceChildren")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AttendanceRecord");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("KinderConnect.Data.Models.AttendanceRecord", b =>
                {
                    b.HasOne("KinderConnect.Data.Models.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KinderConnect.Data.Models.Classroom", "Classroom")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("KinderConnect.Data.Models.Teacher", "Teacher")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Classroom");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("KinderConnect.Data.Models.Child", b =>
                {
                    b.HasOne("KinderConnect.Data.Models.Classroom", "Classroom")
                        .WithMany("Children")
                        .HasForeignKey("ClassroomId");

                    b.HasOne("KinderConnect.Data.Models.ApplicationUser", "ParentGuardian")
                        .WithMany()
                        .HasForeignKey("ParentGuardianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("ParentGuardian");
                });

            modelBuilder.Entity("KinderConnect.Data.Models.ClassroomTeacher", b =>
                {
                    b.HasOne("KinderConnect.Data.Models.Classroom", "Classroom")
                        .WithMany("ClassroomsTeachers")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KinderConnect.Data.Models.Teacher", "Teacher")
                        .WithMany("ClassroomsTeachers")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("KinderConnect.Data.Models.Teacher", b =>
                {
                    b.HasOne("KinderConnect.Data.Models.Qualification", "Qualification")
                        .WithMany()
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KinderConnect.Data.Models.ApplicationUser", "TeacherUser")
                        .WithMany()
                        .HasForeignKey("TeacherUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Qualification");

                    b.Navigation("TeacherUser");
                });

            modelBuilder.Entity("KinderConnect.Data.Models.TeacherQualification", b =>
                {
                    b.HasOne("KinderConnect.Data.Models.Qualification", "Qualification")
                        .WithMany("TeachersQualifications")
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("KinderConnect.Data.Models.Teacher", "Teacher")
                        .WithMany("TeachersQualifications")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Qualification");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("KinderConnect.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("KinderConnect.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KinderConnect.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("KinderConnect.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KinderConnect.Data.Models.AttendanceRecord", b =>
                {
                    b.Navigation("AttendanceChildren");
                });

            modelBuilder.Entity("KinderConnect.Data.Models.Child", b =>
                {
                    b.Navigation("AttendanceChildren");
                });

            modelBuilder.Entity("KinderConnect.Data.Models.Classroom", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("Children");

                    b.Navigation("ClassroomsTeachers");
                });

            modelBuilder.Entity("KinderConnect.Data.Models.Qualification", b =>
                {
                    b.Navigation("TeachersQualifications");
                });

            modelBuilder.Entity("KinderConnect.Data.Models.Teacher", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("ClassroomsTeachers");

                    b.Navigation("TeachersQualifications");
                });
#pragma warning restore 612, 618
        }
    }
}
